from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
import os

pptx_path = "ppts/LisFlood_Cold_Start_Presentation.pptx"
prs = Presentation(pptx_path)

# ---- New Slide: Warm Start Execution (similar to Cold Start slide) ----
slide_layout = prs.slide_layouts[1] # Title and Content
slide_warm = prs.slides.add_slide(slide_layout)
title_warm = slide_warm.shapes.title
if title_warm:
    title_warm.text = "SIMULATION CONFIGURATION: Warm Start Execution"

body_shape = slide_warm.shapes.placeholders[1]
tf = body_shape.text_frame
tf.clear()

p_cmd = tf.paragraphs[0]
p_cmd.text = "Execution Command:"
p_cmd.font.bold = True
p_cmd.font.size = Pt(20)

p_code = tf.add_paragraph()
p_code.text = "docker run --rm -v \"filepath/LisFloodDataPrepScripts\":/input jrce1/lisflood /input/warm_start.xml"
p_code.font.name = "Courier New"
p_code.font.size = Pt(16)
p_code.font.color.rgb = RGBColor(0, 102, 204)
p_code.level = 1

tf.add_paragraph() # spacing

p_what = tf.add_paragraph()
p_what.text = "• What it is: The operational phase of the simulation that continues from a previously stabilized state."
p_what.font.size = Pt(18)

p_how = tf.add_paragraph()
p_how.text = "• How it is configured: Uses warm_start.xml where initial states are loaded from the *.end.nc files produced at the end of the Cold Start run."
p_how.font.size = Pt(18)

p_why = tf.add_paragraph()
p_why.text = "• Why we do it: Bypasses the spin-up period to immediately generate physically realistic hydrological outputs for real-time forecasting."
p_why.font.size = Pt(18)


# ---- New Slide: Initialization Files Explained ----
slide_files = prs.slides.add_slide(slide_layout)
title_files = slide_files.shapes.title
if title_files:
    title_files.text = "COLD TO WARM START TRANSITION: Key State Files"

body_shape_files = slide_files.shapes.placeholders[1]
tf_files = body_shape_files.text_frame
tf_files.clear()

p_intro = tf_files.paragraphs[0]
p_intro.text = "To achieve a Warm Start, various internal states generated by the Cold Start's spin-up are loaded as initial conditions. These files (saved as NetCDF format) capture the 'memory' of the watershed:"
p_intro.font.size = Pt(18)

tf_files.add_paragraph()

files_info = [
    ("Soil & Groundwater States (e.g., wslavg.end.nc, uzavg.end.nc, lzavg.end.nc)", "Contains the stabilized water volume across lower/upper soil layers and groundwater zones."),
    ("Channel Routing State (e.g., chavg.end.nc)", "Represents the exact amount of water flowing within the river channels at the end of the spin-up."),
    ("Interception & Evaporation (e.g., cumi.end.nc, dslr.end.nc)", "Cumulative interception by vegetation and the calculated days since last rain, vital for continuous evaporation modeling."),
    ("Snow & Frost (e.g., frost.end.nc, snow.end.nc)", "Captures accumulated snow cover and frost indices if the cold start ended during winter months.")
]

for fname, fdesc in files_info:
    p_item = tf_files.add_paragraph()
    p_item.text = f"• {fname}"
    p_item.font.bold = True
    p_item.font.size = Pt(16)
    p_item.font.color.rgb = RGBColor(0, 102, 0)
    
    p_desc = tf_files.add_paragraph()
    p_desc.text = f"  {fdesc}"
    p_desc.font.size = Pt(14)
    p_desc.level = 1

# Make it look organized
prs.save(pptx_path)
print("Warm start slides added successfully!")
